services:
  db-development:
    image: postgres:15
    restart: always
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - db-development-data:/var/lib/postgresql/data
    networks:
      - backend-development-network

  db-test:
    image: postgres:15
    env_file:
      - .env.test
    volumes:
      - db-test-data:/var/lib/postgresql/data
    networks:
      - backend-test-network

  db-production:
    image: postgres:15
    restart: always
    env_file:
      - .env.production
    volumes:
      - db-production-data:/var/lib/postgresql/data
    networks:
      - backend-production-network

  backend-development:
    build:
      context: .
      target: development
    env_file:
      - .env.development
    ports:
      - 3000:3000
    depends_on:
      - db-development
    develop:
      watch:
        - action: sync
          path: .
          target: /app/backend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - backend-development-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  backend-test:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    depends_on:
      - db-test
    networks:
      - backend-test-network
    command: sh -c "npx prisma migrate deploy && npm run test:e2e"
  
  backend-production:
    build:
      context: .
      target: production
    env_file:
      - .env.production
    depends_on:
      - db-production
    networks:
      - backend-production-network
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  db-development-data:
  db-test-data:
  db-production-data:

networks:
  backend-development-network:
  backend-test-network:
  backend-production-network:
