services:
  db-test:
    image: postgres:15-alpine
    env_file:
      - .env.test
    volumes:
      - db-test-data:/var/lib/postgresql/data
    networks:
      - backend-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend-test:
    build:
      context: .
      target: test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
        restart: true
    networks:
      - backend-test-network
    command: sh -c "
      npx prisma migrate deploy
      && npm run test
      && npm run test:e2e
      "

volumes:
  db-test-data:

networks:
  backend-test-network:
