services:
  db-development:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - db-development-data:/var/lib/postgresql/data
    networks:
      - backend-development-network

  backend-development:
    build:
      context: .
      target: development
    env_file:
      - .env.development
    ports:
      - 3000:3000
    depends_on:
      - db-development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - backend-development-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  db-development-data:

networks:
  backend-development-network: