import {
  Injectable,
  InternalServerErrorException,
  UnauthorizedException,
} from '@nestjs/common';
import { UsersService } from '../users/users.service';
import { JsonWebTokenError, JwtService } from '@nestjs/jwt';
import {
  AuthenticatedUser,
  CreateJwtPayload,
  RefreshTokenPayload,
} from './types/auth.types';
import { getEnvVar } from '../common/functions';
import { PrismaService } from '../prisma/prisma.service';
import * as ms from 'ms';
import * as bcrypt from 'bcrypt';
import { v4 as uuidv4 } from 'uuid';
import { RefreshToken } from 'generated/prisma';
import { createHash, randomBytes } from 'crypto';

@Injectable()
export class AuthService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly usersService: UsersService,
    private readonly jwtService: JwtService,
  ) {}

  async validateUser(
    username: string,
    password: string,
  ): Promise<AuthenticatedUser> {
    try {
      const user = await this.usersService.findOneForLogin(username);

      const passwordMatches = user
        ? await bcrypt.compare(password, user.password)
        : false;

      if (user && passwordMatches) {
        const { password: _, ...userWithoutPassword } = user;
        return userWithoutPassword;
      } else {
        throw new UnauthorizedException();
      }
    } catch (error) {
      if (error instanceof UnauthorizedException) {
        throw error;
      }
      throw new InternalServerErrorException();
    }
  }

  hashToken(token: string, salt?: string) {
    if (!salt) {
      salt = randomBytes(16).toString('hex');
    }

    const hash = createHash('sha256')
      .update(salt + token)
      .digest('hex');

    return { hash, salt };
  }

  createAccessToken(payload: CreateJwtPayload): string {
    return this.jwtService.sign(payload, {
      secret: getEnvVar('JWT_SECRET'),
      expiresIn: getEnvVar('JWT_EXPIRATION'),
    });
  }

  ensureRefreshTokenMatches(token: string, storedToken: RefreshToken): void {
    const tokenMatch: boolean =
      this.hashToken(token, storedToken.salt).hash === storedToken.tokenHash;

    if (storedToken.revoked === true || !tokenMatch) {
      // security alert : the token has been stolen, altered, not generated by this server or the secret has changed
      throw new UnauthorizedException(
        'Revoked token or does not match with stored one',
      );
    }
  }

  async login(user: AuthenticatedUser) {
    const payload: CreateJwtPayload = { username: user.username, sub: user.id };
    return {
      access_token: this.createAccessToken(payload),
      refresh_token: await this.createAndStoreRefreshToken(user.id),
    };
  }

  async createAndStoreRefreshToken(userId: number): Promise<string> {
    try {
      const jwtRefreshExp = getEnvVar('JWT_REFRESH_EXPIRATION');
      const msJwtRefreshExp = ms(jwtRefreshExp as ms.StringValue);
      const expirationDate = new Date(Date.now() + msJwtRefreshExp);

      if (isNaN(expirationDate.getTime())) {
        throw new InternalServerErrorException('Invalid expiration date');
      }

      const payload = { id: uuidv4(), sub: userId };
      const newRefreshToken = this.jwtService.sign(payload, {
        secret: getEnvVar('JWT_SUPER_SECRET'),
        expiresIn: jwtRefreshExp,
      });

      const { hash, salt } = this.hashToken(newRefreshToken);

      await this.prisma.refreshToken.create({
        data: {
          id: payload.id,
          userId,
          tokenHash: hash,
          salt,
          expiresAt: expirationDate,
        },
      });

      return newRefreshToken;
    } catch (error) {
      throw new InternalServerErrorException();
    }
  }

  async refreshTokens(refreshToken: string) {
    const decodedToken: RefreshTokenPayload =
      this.jwtService.decode(refreshToken);

    try {
      this.jwtService.verify(refreshToken, {
        secret: getEnvVar('JWT_SUPER_SECRET'),
      });

      const storedRefreshToken = await this.prisma.refreshToken.findUnique({
        where: { id: decodedToken.id },
      });

      if (!storedRefreshToken) {
        throw new UnauthorizedException('Refresh token not found in DB');
      }

      const user = await this.usersService.findOneById(
        storedRefreshToken.userId,
      );

      if (!user) {
        throw new UnauthorizedException('User not found in DB');
      }

      this.ensureRefreshTokenMatches(refreshToken, storedRefreshToken);

      await this.prisma.refreshToken.update({
        where: { id: decodedToken.id },
        data: {
          revoked: true,
        },
      });
      const newRefreshToken = await this.createAndStoreRefreshToken(user.id);

      const payload: CreateJwtPayload = {
        username: user.username,
        sub: user.id,
      };

      return {
        access_token: this.createAccessToken(payload),
        refresh_token: newRefreshToken,
      };
    } catch (error) {
      if (
        error instanceof UnauthorizedException ||
        error instanceof JsonWebTokenError
      ) {
        await this.prisma.refreshToken.updateMany({
          where: { userId: decodedToken.sub, revoked: false },
          data: {
            revoked: true,
          },
        });
        throw new UnauthorizedException('Invalid refresh token');
      }

      throw new InternalServerErrorException('An unexpected error occured');
    }
  }
}
